name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: >-
      ${{
        (matrix.targetOs == 'mac' && matrix.targetArch == 'x64') &&
          'macos-13' ||
          (fromJson('{"linux":"ubuntu-22.04","mac":"macos-14","win":"windows-2022"}')[matrix.targetOs])
      }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        targetOs: [linux, mac, win]
        targetArch: [x64]
        include:
          - targetOs: mac
            targetArch: arm64
          - targetOs: win
            targetArch: x86

    steps:
      - name: Install Linux Dependencies
        if: matrix.targetOs == 'linux'
        run: |
          sudo apt update
          sudo apt install -y cmake libgtk-3-dev libnotify-dev libwebkit2gtk-4.0-dev
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang 100
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      # Work around CI bug https://github.com/actions/runner-images/issues/8659.
      - uses: mjp41/workaround8649@c8550b715ccdc17f89c8d5c28d7a48eeff9c94a8
        if: matrix.targetOs == 'linux' && matrix.targetArch == 'x64'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: yarn && yarn dist
